[programs.localnet]
solana_twitter = "BdoQ1KTMk4w9vAwX3JMumqAeuoUsJvYHT6qV2YtvXPKH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/davide/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
